// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chkauvfuchggvdrprrdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoa2F1dmZ1Y2hnZ3ZkcnBycmRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDMzOTAsImV4cCI6MjA3MTk3OTM5MH0.5o6hfPxySZUvP6FMDtVQzXuC_3hIttwS4XZWLlvfZgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});